name: starml
channels:
  - conda-forge
  - bioconda
dependencies:
  
  - python=3.11

  
  - numpy>=1.23
  - pandas>=1.5
  - scipy>=1.10
  - scikit-learn>=1.2
  - biopython>=1.79
  - joblib>=1.3
  - xgboost>=1.7

  
  - ncbi-datasets-cli        
  - bedtools                 

  
  - tqdm

