{% set name = "starml" %}
{% set version = "0.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: python -m pip install . --no-deps -v

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.9
    - numpy >=1.23
    - pandas >=1.5
    - scipy >=1.10
    - joblib >=1.3
    - scikit-learn >=1.2
    - biopython >=1.79
    - xgboost >=1.7
    - ncbi-datasets-cli      
    - bedtools               

test:
  commands:
    - starml --help
  imports:
    - starml

about:
  home: https://github.com/VKotsira/sTarML
  license: MIT
  summary: "sTarML: A Sequence-Based ML framework for predicting bacterial sRNA–mRNA interactions."
  description: |
    sTarML downloads genomes/annotations with NCBI Datasets, prepares features,
    and predicts sRNA–mRNA interactions using bundled vectorizers/scalers and model.
  doc_url: https://github.com/VKotsira/sTarML#readme
  dev_url: https://github.com/VKotsira/sTarML

extra:
  recipe-maintainers:
    - <vkotsira>

